---
# tasks file for Dell-Networking.dellos-lag
- name: "Provisioning LAG configuration for dellos9"
  dellos9_config:
    src: dellos9_lag.j2
    provider: "{{ cli }}"
#  notify: save config os9
  when: ansible_net_os_name == "dellos9"
  register: output

- name: "Provisioning LAG configuration for dellos10"
  dellos10_config:
    src: dellos10_lag.j2
    provider: "{{ cli }}"
#  notify: save config os10
  when: ansible_net_os_name == "dellos10"
  register: output

- name: "Provisioning LAG configuration for dellos6"
  dellos6_config:
    src: dellos6_lag.j2
    provider: "{{ cli }}"
#  notify: save config os6
  when: ansible_net_os_name == "dellos6"
  register: output







